# #
#  MT-Wapens Configuratie Files
# #
# Zorg ervoor dat je bij 'damage en attackspeed' altijd een DECIMAAL invult.
# #
# #
weapon-lore: Minetopia - Officieel Minetopia Wapen
ammo-lore: Minetopia - Officieel Minetopia Bullet
weapons:
  deserteagle:
    name: '&8Desert Eagle'
    ammo-name: Desert Eagle Ammo
    damage: 2.0
    max-ammo: 7
    attackspeed: 1.0
  magnum44:
    name: '&8Magnum 44'
    ammo-name: Magnum 44 Ammo
    damage: 2.5
    max-ammo: 8
    attackspeed: 1.0
  waltherp99:
    name: '&8Walther P99'
    ammo-name: Walther P99 Ammo
    damage: 3.0
    max-ammo: 10
    attackspeed: 1.0
  glock19:
    name: '&8Glock 19'
    ammo-name: Glock 19 Ammo
    damage: 3.3
    max-ammo: 10
    attackspeed: 1.0
  m16a4:
    name: '&8M16A4'
    ammo-name: M16A4 Ammo
    damage: 3.7
    max-ammo: 25
    attackspeed: 1.0
messages:
  first-color: "&6"
  second-color: "&c"
  shot:
    you: "&cJe hebt &4<player> &cgeraakt met jouw schot!"
    other: "&cJe bent beschoten door &4<player>&c."