name: MT-Wapens
version: ${project.version}
description: Add weapons to your Minecraft server
website: https://www.spigotmc.org/resources/76350/
main: com.jazzkuh.mtwapens.Main
author: Jazzkuh
api-version: 1.16
commands:
  getweapon:
    description: GetWeapon command
  getammo:
    description: GetAmmo command
  mtwapens:
    aliases: [weapon, mtwapen]
    description: Main MTWapens command
  giveweapon:
    description: GiveWeapon command