name: MT-Wapens
description: Voeg wapens toe aan jouw server
website: https://www.spigotmc.org/resources/76350/
version: 1.0.8
main: com.jazzkuh.main.Main
authors: [Jazzkuh]
commands:
  weapon:
    aliases: [mtwapens, mt-wapens, weapons]
